/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from 'mongoose';

/**
 * Lean version of BilateralContractPolicyPermissionDutyConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const bilateralcontractpolicypermissiondutyObject = bilateralcontractpolicypermissionduty.toObject();
 * ```
 */
export type BilateralContractPolicyPermissionDutyConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of BilateralContractPolicyPermissionDutyConsequenceConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyPermissionDutyConsequenceDocument.toObject()`.
 * ```
 * const bilateralcontractpolicypermissiondutyconsequenceObject = bilateralcontractpolicypermissiondutyconsequence.toObject();
 * ```
 */
export type BilateralContractPolicyPermissionDutyConsequenceConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of BilateralContractPolicyPermissionDutyConsequenceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const bilateralcontractpolicypermissiondutyObject = bilateralcontractpolicypermissionduty.toObject();
 * ```
 */
export type BilateralContractPolicyPermissionDutyConsequence = {
  action?: string;
  constraint: BilateralContractPolicyPermissionDutyConsequenceConstraint[];
  consequence: any[];
};

/**
 * Lean version of BilateralContractPolicyPermissionDutyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyPermissionDocument.toObject()`.
 * ```
 * const bilateralcontractpolicypermissionObject = bilateralcontractpolicypermission.toObject();
 * ```
 */
export type BilateralContractPolicyPermissionDuty = {
  action?: string;
  constraint: BilateralContractPolicyPermissionDutyConstraint[];
  consequence: BilateralContractPolicyPermissionDutyConsequence[];
};

/**
 * Lean version of BilateralContractPolicyPermissionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyPermissionDocument.toObject()`.
 * ```
 * const bilateralcontractpolicypermissionObject = bilateralcontractpolicypermission.toObject();
 * ```
 */
export type BilateralContractPolicyPermissionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of BilateralContractPolicyPermissionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyDocument.toObject()`.
 * ```
 * const bilateralcontractpolicyObject = bilateralcontractpolicy.toObject();
 * ```
 */
export type BilateralContractPolicyPermission = {
  action?: string;
  target?: string;
  duty: BilateralContractPolicyPermissionDuty[];
  constraint: BilateralContractPolicyPermissionConstraint[];
};

/**
 * Lean version of BilateralContractPolicyProhibitionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyProhibitionDocument.toObject()`.
 * ```
 * const bilateralcontractpolicyprohibitionObject = bilateralcontractpolicyprohibition.toObject();
 * ```
 */
export type BilateralContractPolicyProhibitionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of BilateralContractPolicyProhibitionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractPolicyDocument.toObject()`.
 * ```
 * const bilateralcontractpolicyObject = bilateralcontractpolicy.toObject();
 * ```
 */
export type BilateralContractPolicyProhibition = {
  action?: string;
  target?: string;
  constraint: BilateralContractPolicyProhibitionConstraint[];
};

/**
 * Lean version of BilateralContractPolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractPolicy = {
  uid?: string;
  description?: string;
  permission: BilateralContractPolicyPermission[];
  prohibition: BilateralContractPolicyProhibition[];
};

/**
 * Lean version of BilateralContractPurposeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractPurpose = {
  uid?: string;
  purpose?: string;
  action?: string;
  assigner?: string;
  assignee?: string;
  piiCategory: string[];
  consentType?: string;
  primaryPurpose?: boolean;
  termination?: string;
  thirdPartyDisclosure?: boolean;
  thirdPartyName?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BilateralContractSignatureDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractSignature = {
  did: string;
  party: string;
  value: string;
  date?: Date;
};

/**
 * Lean version of BilateralContractRevokedSignatureDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractRevokedSignature = {
  did: string;
  party: string;
  value: string;
  date?: Date;
};

/**
 * Lean version of BilateralContractNegotiatorDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractNegotiator = {
  did?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BilateralContractDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BilateralContractDocument.toObject()`. To avoid conflicts with model names, use the type alias `BilateralContractObject`.
 * ```
 * const bilateralcontractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContract = {
  uid?: string;
  dataProvider?: string;
  dataConsumer?: string;
  serviceOffering?: string;
  profile?: string;
  policy: BilateralContractPolicy[];
  purpose: BilateralContractPurpose[];
  signatures: BilateralContractRevokedSignature[];
  revokedSignatures: BilateralContractRevokedSignature[];
  negotiators: BilateralContractNegotiator[];
  status?: 'signed' | 'revoked' | 'under_negotiation' | 'pending';
  terminationAndValidity: {
    effectiveDate?: Date;
    terminationPeriod?: Date;
  };
  limitationOfLiability?: Date;
  termsAndConditions?: string;
  jsonLD?: string;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of BilateralContractDocument (type alias of `BilateralContract`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { BilateralContract } from "../models"
 * import { BilateralContractObject } from "../interfaces/mongoose.gen.ts"
 *
 * const bilateralcontractObject: BilateralContractObject = bilateralcontract.toObject();
 * ```
 */
export type BilateralContractObject = BilateralContract;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type BilateralContractQuery = mongoose.Query<
  any,
  BilateralContractDocument,
  BilateralContractQueries
> &
  BilateralContractQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `BilateralContractSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type BilateralContractQueries = {};

export type BilateralContractMethods = {};

export type BilateralContractStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BilateralContract = mongoose.model<BilateralContractDocument, BilateralContractModel>("BilateralContract", BilateralContractSchema);
 * ```
 */
export type BilateralContractModel = mongoose.Model<
  BilateralContractDocument,
  BilateralContractQueries
> &
  BilateralContractStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new BilateralContract schema instances:
 * ```
 * const BilateralContractSchema: BilateralContractSchema = new mongoose.Schema({ ... })
 * ```
 */
export type BilateralContractSchema = mongoose.Schema<
  BilateralContractDocument,
  BilateralContractModel,
  BilateralContractMethods,
  BilateralContractQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyPermissionDutyDocument["constraint"]` element.
 */
export type BilateralContractPolicyPermissionDutyConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyPermissionDutyConsequenceDocument["constraint"]` element.
 */
export type BilateralContractPolicyPermissionDutyConsequenceConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyPermissionDutyDocument["consequence"]` element.
 */
export type BilateralContractPolicyPermissionDutyConsequenceDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionDutyConsequenceConstraintDocument>;
    consequence: mongoose.Types.Array<any>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyPermissionDocument["duty"]` element.
 */
export type BilateralContractPolicyPermissionDutyDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionDutyConstraintDocument>;
    consequence: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionDutyConsequenceDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyPermissionDocument["constraint"]` element.
 */
export type BilateralContractPolicyPermissionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyDocument["permission"]` element.
 */
export type BilateralContractPolicyPermissionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    duty: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionDutyDocument>;
    constraint: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyProhibitionDocument["constraint"]` element.
 */
export type BilateralContractPolicyProhibitionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractPolicyDocument["prohibition"]` element.
 */
export type BilateralContractPolicyProhibitionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    constraint: mongoose.Types.DocumentArray<BilateralContractPolicyProhibitionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractDocument["policy"]` element.
 */
export type BilateralContractPolicyDocument =
  mongoose.Types.Subdocument<any> & {
    uid?: string;
    description?: string;
    permission: mongoose.Types.DocumentArray<BilateralContractPolicyPermissionDocument>;
    prohibition: mongoose.Types.DocumentArray<BilateralContractPolicyProhibitionDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractDocument["purpose"]` element.
 */
export type BilateralContractPurposeDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    uid?: string;
    purpose?: string;
    action?: string;
    assigner?: string;
    assignee?: string;
    piiCategory: mongoose.Types.Array<string>;
    consentType?: string;
    primaryPurpose?: boolean;
    termination?: string;
    thirdPartyDisclosure?: boolean;
    thirdPartyName?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractDocument["signatures"]` element.
 */
export type BilateralContractSignatureDocument =
  mongoose.Types.Subdocument<any> & {
    did: string;
    party: string;
    value: string;
    date?: Date;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractDocument["revokedSignatures"]` element.
 */
export type BilateralContractRevokedSignatureDocument =
  mongoose.Types.Subdocument<any> & {
    did: string;
    party: string;
    value: string;
    date?: Date;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BilateralContractDocument["negotiators"]` element.
 */
export type BilateralContractNegotiatorDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    did?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BilateralContract = mongoose.model<BilateralContractDocument, BilateralContractModel>("BilateralContract", BilateralContractSchema);
 * ```
 */
export type BilateralContractDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  BilateralContractQueries
> &
  BilateralContractMethods & {
    uid?: string;
    dataProvider?: string;
    dataConsumer?: string;
    serviceOffering?: string;
    profile?: string;
    policy: mongoose.Types.DocumentArray<BilateralContractPolicyDocument>;
    purpose: mongoose.Types.DocumentArray<BilateralContractPurposeDocument>;
    signatures: mongoose.Types.DocumentArray<BilateralContractRevokedSignatureDocument>;
    revokedSignatures: mongoose.Types.DocumentArray<BilateralContractRevokedSignatureDocument>;
    negotiators: mongoose.Types.DocumentArray<BilateralContractNegotiatorDocument>;
    status?: 'signed' | 'revoked' | 'under_negotiation' | 'pending';
    terminationAndValidity: {
      effectiveDate?: Date;
      terminationPeriod?: Date;
    };
    limitationOfLiability?: Date;
    termsAndConditions?: string;
    jsonLD?: string;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ContractServiceOfferingPolicyPermissionDutyConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicypermissiondutyObject = contractserviceofferingpolicypermissionduty.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermissionDutyConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractServiceOfferingPolicyPermissionDutyConsequenceConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyPermissionDutyConsequenceDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicypermissiondutyconsequenceObject = contractserviceofferingpolicypermissiondutyconsequence.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermissionDutyConsequenceConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractServiceOfferingPolicyPermissionDutyConsequenceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicypermissiondutyObject = contractserviceofferingpolicypermissionduty.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermissionDutyConsequence = {
  action?: string;
  constraint: ContractServiceOfferingPolicyPermissionDutyConsequenceConstraint[];
  consequence: any[];
};

/**
 * Lean version of ContractServiceOfferingPolicyPermissionDutyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyPermissionDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicypermissionObject = contractserviceofferingpolicypermission.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermissionDuty = {
  action?: string;
  constraint: ContractServiceOfferingPolicyPermissionDutyConstraint[];
  consequence: ContractServiceOfferingPolicyPermissionDutyConsequence[];
};

/**
 * Lean version of ContractServiceOfferingPolicyPermissionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyPermissionDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicypermissionObject = contractserviceofferingpolicypermission.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermissionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractServiceOfferingPolicyPermissionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicyObject = contractserviceofferingpolicy.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyPermission = {
  action?: string;
  target?: string;
  duty: ContractServiceOfferingPolicyPermissionDuty[];
  constraint: ContractServiceOfferingPolicyPermissionConstraint[];
};

/**
 * Lean version of ContractServiceOfferingPolicyProhibitionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyProhibitionDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicyprohibitionObject = contractserviceofferingpolicyprohibition.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyProhibitionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractServiceOfferingPolicyProhibitionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingPolicyDocument.toObject()`.
 * ```
 * const contractserviceofferingpolicyObject = contractserviceofferingpolicy.toObject();
 * ```
 */
export type ContractServiceOfferingPolicyProhibition = {
  action?: string;
  target?: string;
  constraint: ContractServiceOfferingPolicyProhibitionConstraint[];
};

/**
 * Lean version of ContractServiceOfferingPolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractServiceOfferingDocument.toObject()`.
 * ```
 * const contractserviceofferingObject = contractserviceoffering.toObject();
 * ```
 */
export type ContractServiceOfferingPolicy = {
  uid?: string;
  description?: string;
  permission: ContractServiceOfferingPolicyPermission[];
  prohibition: ContractServiceOfferingPolicyProhibition[];
};

/**
 * Lean version of ContractServiceOfferingDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractServiceOffering = {
  participant: string;
  serviceOffering: string;
  policies: ContractServiceOfferingPolicy[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionDutyConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicypermissiondutyObject = contractrolesandobligationpolicypermissionduty.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermissionDutyConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionDutyConsequenceConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyPermissionDutyConsequenceDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicypermissiondutyconsequenceObject = contractrolesandobligationpolicypermissiondutyconsequence.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermissionDutyConsequenceConstraint =
  {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionDutyConsequenceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyPermissionDutyDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicypermissiondutyObject = contractrolesandobligationpolicypermissionduty.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermissionDutyConsequence = {
  action?: string;
  constraint: ContractRolesAndObligationPolicyPermissionDutyConsequenceConstraint[];
  consequence: any[];
};

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionDutyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyPermissionDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicypermissionObject = contractrolesandobligationpolicypermission.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermissionDuty = {
  action?: string;
  constraint: ContractRolesAndObligationPolicyPermissionDutyConstraint[];
  consequence: ContractRolesAndObligationPolicyPermissionDutyConsequence[];
};

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyPermissionDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicypermissionObject = contractrolesandobligationpolicypermission.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermissionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractRolesAndObligationPolicyPermissionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicyObject = contractrolesandobligationpolicy.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyPermission = {
  action?: string;
  target?: string;
  duty: ContractRolesAndObligationPolicyPermissionDuty[];
  constraint: ContractRolesAndObligationPolicyPermissionConstraint[];
};

/**
 * Lean version of ContractRolesAndObligationPolicyProhibitionConstraintDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyProhibitionDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicyprohibitionObject = contractrolesandobligationpolicyprohibition.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyProhibitionConstraint = {
  '@type'?: string;
  leftOperand?: string;
  operator?: string;
  rightOperand?: any;
};

/**
 * Lean version of ContractRolesAndObligationPolicyProhibitionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationPolicyDocument.toObject()`.
 * ```
 * const contractrolesandobligationpolicyObject = contractrolesandobligationpolicy.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicyProhibition = {
  action?: string;
  target?: string;
  constraint: ContractRolesAndObligationPolicyProhibitionConstraint[];
};

/**
 * Lean version of ContractRolesAndObligationPolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractRolesAndObligationDocument.toObject()`.
 * ```
 * const contractrolesandobligationObject = contractrolesandobligation.toObject();
 * ```
 */
export type ContractRolesAndObligationPolicy = {
  uid?: string;
  description?: string;
  permission: ContractRolesAndObligationPolicyPermission[];
  prohibition: ContractRolesAndObligationPolicyProhibition[];
};

/**
 * Lean version of ContractRolesAndObligationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractRolesAndObligation = {
  role?: string;
  policies: ContractRolesAndObligationPolicy[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ContractServiceChainDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractServiceChain = {
  catalogId: string;
  services: any[];
  status?: 'active' | 'inactive';
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ContractPurposeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractPurpose = {
  uid?: string;
  purpose?: string;
  action?: string;
  assigner?: string;
  assignee?: string;
  purposeCategory?: string;
  consentType?: string;
  piiCategory?: string;
  primaryPurpose?: string;
  termination?: string;
  thirdPartyDisclosure?: string;
  thirdPartyName?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ContractMemberDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractMember = {
  participant: string;
  role: string;
  signature: string;
  date?: Date;
};

/**
 * Lean version of ContractRevokedMemberDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type ContractRevokedMember = {
  participant: string;
  role: string;
  signature: string;
  date?: Date;
};

/**
 * Lean version of ContractDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContractDocument.toObject()`. To avoid conflicts with model names, use the type alias `ContractObject`.
 * ```
 * const contractObject = contract.toObject();
 * ```
 */
export type Contract = {
  uid?: string;
  profile?: string;
  ecosystem?: string;
  orchestrator?: string;
  serviceOfferings: ContractServiceOffering[];
  rolesAndObligations: ContractRolesAndObligation[];
  serviceChains: ContractServiceChain[];
  purpose: ContractPurpose[];
  members: ContractRevokedMember[];
  revokedMembers: ContractRevokedMember[];
  status?: 'signed' | 'revoked' | 'pending';
  jsonLD?: string;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ContractDocument (type alias of `Contract`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Contract } from "../models"
 * import { ContractObject } from "../interfaces/mongoose.gen.ts"
 *
 * const contractObject: ContractObject = contract.toObject();
 * ```
 */
export type ContractObject = Contract;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ContractQuery = mongoose.Query<
  any,
  ContractDocument,
  ContractQueries
> &
  ContractQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ContractSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ContractQueries = {};

export type ContractMethods = {};

export type ContractStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contract = mongoose.model<ContractDocument, ContractModel>("Contract", ContractSchema);
 * ```
 */
export type ContractModel = mongoose.Model<ContractDocument, ContractQueries> &
  ContractStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Contract schema instances:
 * ```
 * const ContractSchema: ContractSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ContractSchema = mongoose.Schema<
  ContractDocument,
  ContractModel,
  ContractMethods,
  ContractQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyPermissionDutyDocument["constraint"]` element.
 */
export type ContractServiceOfferingPolicyPermissionDutyConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyPermissionDutyConsequenceDocument["constraint"]` element.
 */
export type ContractServiceOfferingPolicyPermissionDutyConsequenceConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyPermissionDutyDocument["consequence"]` element.
 */
export type ContractServiceOfferingPolicyPermissionDutyConsequenceDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionDutyConsequenceConstraintDocument>;
    consequence: mongoose.Types.Array<any>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyPermissionDocument["duty"]` element.
 */
export type ContractServiceOfferingPolicyPermissionDutyDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionDutyConstraintDocument>;
    consequence: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionDutyConsequenceDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyPermissionDocument["constraint"]` element.
 */
export type ContractServiceOfferingPolicyPermissionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyDocument["permission"]` element.
 */
export type ContractServiceOfferingPolicyPermissionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    duty: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionDutyDocument>;
    constraint: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyProhibitionDocument["constraint"]` element.
 */
export type ContractServiceOfferingPolicyProhibitionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingPolicyDocument["prohibition"]` element.
 */
export type ContractServiceOfferingPolicyProhibitionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    constraint: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyProhibitionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractServiceOfferingDocument["policies"]` element.
 */
export type ContractServiceOfferingPolicyDocument =
  mongoose.Types.Subdocument<any> & {
    uid?: string;
    description?: string;
    permission: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyPermissionDocument>;
    prohibition: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyProhibitionDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["serviceOfferings"]` element.
 */
export type ContractServiceOfferingDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    participant: string;
    serviceOffering: string;
    policies: mongoose.Types.DocumentArray<ContractServiceOfferingPolicyDocument>;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyPermissionDutyDocument["constraint"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionDutyConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyPermissionDutyConsequenceDocument["constraint"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionDutyConsequenceConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyPermissionDutyDocument["consequence"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionDutyConsequenceDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionDutyConsequenceConstraintDocument>;
    consequence: mongoose.Types.Array<any>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyPermissionDocument["duty"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionDutyDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    constraint: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionDutyConstraintDocument>;
    consequence: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionDutyConsequenceDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyPermissionDocument["constraint"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyDocument["permission"]` element.
 */
export type ContractRolesAndObligationPolicyPermissionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    duty: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionDutyDocument>;
    constraint: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyProhibitionDocument["constraint"]` element.
 */
export type ContractRolesAndObligationPolicyProhibitionConstraintDocument =
  mongoose.Types.Subdocument<any> & {
    '@type'?: string;
    leftOperand?: string;
    operator?: string;
    rightOperand?: any;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationPolicyDocument["prohibition"]` element.
 */
export type ContractRolesAndObligationPolicyProhibitionDocument =
  mongoose.Types.Subdocument<any> & {
    action?: string;
    target?: string;
    constraint: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyProhibitionConstraintDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractRolesAndObligationDocument["policies"]` element.
 */
export type ContractRolesAndObligationPolicyDocument =
  mongoose.Types.Subdocument<any> & {
    uid?: string;
    description?: string;
    permission: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyPermissionDocument>;
    prohibition: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyProhibitionDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["rolesAndObligations"]` element.
 */
export type ContractRolesAndObligationDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    role?: string;
    policies: mongoose.Types.DocumentArray<ContractRolesAndObligationPolicyDocument>;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["serviceChains"]` element.
 */
export type ContractServiceChainDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    catalogId: string;
    services: mongoose.Types.Array<any>;
    status?: 'active' | 'inactive';
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["purpose"]` element.
 */
export type ContractPurposeDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    uid?: string;
    purpose?: string;
    action?: string;
    assigner?: string;
    assignee?: string;
    purposeCategory?: string;
    consentType?: string;
    piiCategory?: string;
    primaryPurpose?: string;
    termination?: string;
    thirdPartyDisclosure?: string;
    thirdPartyName?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["members"]` element.
 */
export type ContractMemberDocument = mongoose.Types.Subdocument<any> & {
  participant: string;
  role: string;
  signature: string;
  date?: Date;
};

/**
 * Mongoose Subdocument type
 *
 * Type of `ContractDocument["revokedMembers"]` element.
 */
export type ContractRevokedMemberDocument = mongoose.Types.Subdocument<any> & {
  participant: string;
  role: string;
  signature: string;
  date?: Date;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contract = mongoose.model<ContractDocument, ContractModel>("Contract", ContractSchema);
 * ```
 */
export type ContractDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ContractQueries
> &
  ContractMethods & {
    uid?: string;
    profile?: string;
    ecosystem?: string;
    orchestrator?: string;
    serviceOfferings: mongoose.Types.DocumentArray<ContractServiceOfferingDocument>;
    rolesAndObligations: mongoose.Types.DocumentArray<ContractRolesAndObligationDocument>;
    serviceChains: mongoose.Types.DocumentArray<ContractServiceChainDocument>;
    purpose: mongoose.Types.DocumentArray<ContractPurposeDocument>;
    members: mongoose.Types.DocumentArray<ContractRevokedMemberDocument>;
    revokedMembers: mongoose.Types.DocumentArray<ContractRevokedMemberDocument>;
    status?: 'signed' | 'revoked' | 'pending';
    jsonLD?: string;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module 'mongoose' {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
