name: Publish to Docker
on:
  push:
    branches:
      - main
      - ci
permissions:
  contents: read
  packages: write
jobs:
  publish:
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            dev-latest
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
        env:
          ENV MONGO_URL: mongodb://mongodb:27017/contract-dev
          ENV MONGO_TEST_URL: mongodb://mongodb:27017/contract-test-cases
          ENV CATALOG_REGISTRY_URL: https://raw.githubusercontent.com/Prometheus-X-association/reference-models/main/src/references/rules/
          ENV CATALOG_REGISTRY_FILE_EXT: json